### ISSUE TITLE
Debug Display Visual Bug

### ISSUE THREAD

**Issue by chordatgh1234** [UCSolarCarTeam/Epsilon-Dashboard#143]
Debug display Control Menu has the Driver Lights and Alive label swapped. 
![image](https://user-images.githubusercontent.com/32528451/48972573-514a2700-efea-11e8-8bfa-5411b4acb5ce.png)

**Comment by Reddragoneer1** [comment]
What is the upper limit for High cell ID and Low vell ID?

**Comment by bill-luu** [comment]
Definitely a double digit amount!

**Comment by bill-luu** [comment]
The original intention of the Alive section is to denote if a board is actually sending messages or not. Since all three boards use the alive indicator, it was organized like that so we could save space.
