### ISSUE TITLE
Dashboard is not compatible with higher resolutions

### ISSUE THREAD

**Issue by ThomasVy** [UCSolarCarTeam/Epsilon-Dashboard#144]
![screenshot from 2018-11-29 19-02-32](https://user-images.githubusercontent.com/32784962/49263871-6f0ff580-f409-11e8-9b74-51dcfbfdb249.png)

My resolution is 3200 x 1800 and this is what it shows.

**Comment by bill-luu** [comment]
@ThomasVy did this get fixed by #225?

**Comment by ThomasVy** [comment]
Yes it did.

**Comment by bill-luu** [comment]
<3
