### ISSUE TITLE
Precharge state circle never changes

### ISSUE THREAD

**Issue by nicholasc120** [UCSolarCarTeam/Epsilon-Dashboard#156]
The design implies that it's meant to indicate whether or not it's alive but it never changes. However, the purpose of it is unclear so it could be working properly, but it doesn't seem to serve any purpose either.
![image](https://user-images.githubusercontent.com/44730168/52168419-7a242200-26e7-11e9-9860-d55203fa8e2a.png)
This is in race mode

**Comment by bill-luu** [comment]
I think we can just remove it..... nothing is attached to it at all
