### ISSUE TITLE
Bus Voltage and Bus Current are rounded differently

### ISSUE THREAD

**Issue by nicholasc120** [UCSolarCarTeam/Epsilon-Dashboard#157]
Bus Current is rounded to 3 decimals but voltage is only rounded to two. This causes the text to be cut off a bit in race mode
![image](https://user-images.githubusercontent.com/44730168/52168437-b22b6500-26e7-11e9-90ae-f48f7bcaa640.png)

**Comment by bill-luu** [comment]
Let's round current to 2 decimals

**Comment by bill-luu** [comment]
Addressed in #160
