### ISSUE TITLE
Low and Avg cell voltage is labelled with wrong units

### ISSUE THREAD

**Issue by nicholasc120** [UCSolarCarTeam/Epsilon-Dashboard#158]
In display mode, units are labelled with V instead of mV

**Comment by bill-luu** [comment]
We should change the mV label in race mode to V. I took a quick look at the BMS manual and we're getting the data in mV, but the values we're getting are cap out at 6.5 volts, so we should convert them both to V like in the debug display.

Right now though I think they would be displaying 6500 V or 6500 mV on race & display mode, lol
