### ISSUE TITLE
Unit Color Inconsistency

### ISSUE THREAD

**Issue by nicholasc120** [UCSolarCarTeam/Epsilon-Dashboard#214]
Some of the units are in grey and some of the units are in white. I think
white should be reserved for data, and all the units should be grey.

some units are like this:
![image](https://user-images.githubusercontent.com/44730168/59152783-a985cb00-8a08-11e9-881e-0fb019e6e9fa.png)

I think they should look like this:
![image](https://user-images.githubusercontent.com/44730168/59152800-0bdecb80-8a09-11e9-83a4-a0fda00c5447.png)
This occurs in the display mode

**Comment by bill-luu** [comment]
I think it should actually be the same color as the data, as it's a part of the changing information.

Static information would then be grey.
