### ISSUE TITLE
Max Temp Label should be below the data

### ISSUE THREAD

**Issue by nicholasc120** [UCSolarCarTeam/Epsilon-Dashboard#217]
The format should match all the adjacent labels
![image](https://user-images.githubusercontent.com/44730168/59152899-e6eb5800-8a0a-11e9-804b-16edcd22dae0.png)
This occurs in the display mode

**Comment by bill-luu** [comment]
The race mode has the Max and Low cell titles above it, I think we should move the low cell one up.
