### ISSUE TITLE
Temperature naming inconsistency

### ISSUE THREAD

**Issue by nicholasc120** [UCSolarCarTeam/Epsilon-Dashboard#221]
In the telemetry test tool, the field is called High Temp but in the display dashboard it's max temp.
![image](https://user-images.githubusercontent.com/44730168/59152969-9b39ae00-8a0c-11e9-80be-7ed815bd514b.png)

**Comment by bill-luu** [comment]
Do you mean low voltage?

**Comment by nicholasc120** [comment]
Whoops, I named the issue wrong

**Comment by bill-luu** [comment]
Still not sure what the issue is. Is it the `high temp` field on the test tool changing the `Max Temp` field on the dashboard?

**Comment by nicholasc120** [comment]
yes
