### ISSUE TITLE
Integrate Debug Display

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Dashboard#48]
As previously announced, the Debug Display project will get integrated to the Dashboard. 

- The Viewlayer components in the `tabUi` branch (https://github.com/UCSolarCarTeam/Epsilon-Debug-Display/pull/1/files) branch needs to be integrated to the project. 
- Afterwards, the command line arguments of the Dashboard need to be updated
- The README also needs to be updated for instructions.

**Comment by enochtsang** [comment]
New plan, desktop will run hermes locally and convert to json, send to localhost, then run webserver to display the ui.

**Comment by bill-luu** [comment]
Closed by mistake, woops!

**Comment by bill-luu** [comment]
Addressed in #53
