### ISSUE TITLE
Qt 5.6 Upgrade

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Dashboard#57]
@safasyed please post screenshots and any relevant info for any issues you find when you're trying to compile it on QT 5.6.

Once we have the info (and have tried to recreate the issues on other machines), @badeniran can you try and help resolve them?

**Comment by safasyed** [comment]
![epsilon dashboard errors](https://user-images.githubusercontent.com/22860648/27255198-bdd25406-5356-11e7-9dbc-135a112d6dd7.png)
