### ISSUE TITLE
HomePage Ui

### ISSUE THREAD

**Issue by ikazuka36** [UCSolarCarTeam/Epsilon-Dashboard#61]
Replacing regular QPushButton with correspond images as well as adding background

**Comment by ikazuka36** [comment]
![19679592_10203522434019571_761210999_n](https://user-images.githubusercontent.com/17913227/28346504-bd4a2cf6-6bee-11e7-8134-47eab679c5e2.jpg)

**Comment by bill-luu** [comment]
![image](https://user-images.githubusercontent.com/15304203/35595869-607a30c6-05d5-11e8-9684-cf198f52eccd.png)
