### ISSUE TITLE
mpptPowerReceived

### ISSUE THREAD

**Issue by badeniran** [UCSolarCarTeam/Epsilon-Dashboard#67]
Find out the purpose of mpptPowerReceived and if it is needed for debug display.

**Comment by bill-luu** [comment]
mpptPowerRecieved was leftover code and does not work, we will have to remove it, and alter the calculations that are using it.

**Comment by bill-luu** [comment]
So mpptPowerRecieved was used by the DisplayDashboardView to set the labels of the Power In/Power out:

void DisplayDashboardView::mpptPowerReceived(double mpptPower)
{
    ui_.powerInLabel().setNum(mpptPower);
    ui_.powerOutLabel().setNum(ui_.netPowerLabel().text().toDouble() - mpptPower);
}

But looking at what was supposed to go on the dashboard at the time:

![image](https://user-images.githubusercontent.com/15304203/30456143-b3b7d8d4-995f-11e7-8348-153143132a53.png)

It looks like the proper values should have been from the battery section.......that got updated with the Orion change. Is there another way to calculate power in/power out? Or is it actually supposed to be calculated by the array voltage/current of the mppts, in which case would we need to average it out between the three mppts?

**Comment by bill-luu** [comment]
Asked the electrical team, Power In would be the SUM of all three of the mppt powers (ArrayVoltage * ArrayCurrent).

**Comment by bill-luu** [comment]
Remove all references to `mpptPowerRecieved` and replace with the `MpptView::mpptReceived` in the Debug display.
