### ISSUE TITLE
Missing Signals

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Dashboard#79]
There a few "No such signal" errors occurring when running the program.

**Comment by enochtsang** [comment]
Can you put the exact log messages here?

**Comment by jeffh1996** [comment]
**Signal errors when running in ANY mode (race,display, and debug)**

QObject::connect: Incompatible sender/receiver arguments
        I_BatteryFaultsData::batteryLimitFlagsReceived(BatteryLimitFlags) --> BatteryFaultsPresenter::errorFlagsReceived(BatteryErrorFlags)
QObject::connect: No such signal I_KeyMotorData::motorSetCurrentReceived(double setCurrent) in ../../Epsilon-Dashboard/PresenterLayer/KeyMotorPresenter/KeyMotorPresenter.cpp:16
QObject::connect: No such signal I_KeyMotorData::motorActualSpeedReceived(double actualSpeed) in ../../Epsilon-Dashboard/PresenterLayer/KeyMotorPresenter/KeyMotorPresenter.cpp:18
QObject::connect: No such signal I_KeyMotorData::motorBusVoltageReceived(double busVoltage) in ../../Epsilon-Dashboard/PresenterLayer/KeyMotorPresenter/KeyMotorPresenter.cpp:20
QObject::connect: No such signal I_KeyMotorData::motorBusCurrentReceived(double busCurrent) in ../../Epsilon-Dashboard/PresenterLayer/KeyMotorPresenter/KeyMotorPresenter.cpp:22
QObject::connect: No such signal I_MpptData::mpptPowerReceived(double) in ../../Epsilon-Dashboard/PresenterLayer/MpptPresenter/MpptPresenter.cpp:13

**Additional errors when running in debug mode**
QObject::connect: No such slot MpptView::mpptPowerReceived(double) in ../../Epsilon-Dashboard/ViewLayer/DebugDisplay/MPPTPage/MPPTView/MpptView.cpp:37

**Additional errors when running in display mode**
QObject::connect: No such signal KeyMotorPresenter::motorSetCurrentReceived(double setCurrent) in ../../Epsilon-Dashboard/ViewLayer/DisplayDashboard/DisplayDashboardView/DisplayDashboardView.cpp:81
QObject::connect: No such signal KeyMotorPresenter::motorActualSpeedReceived(double actualSpeed) in ../../Epsilon-Dashboard/ViewLayer/DisplayDashboard/DisplayDashboardView/DisplayDashboardView.cpp:83
QObject::connect: No such signal KeyMotorPresenter::motorBusVoltageReceived(double busVoltage) in ../../Epsilon-Dashboard/ViewLayer/DisplayDashboard/DisplayDashboardView/DisplayDashboardView.cpp:85
QObject::connect: No such signal KeyMotorPresenter::motorBusCurrentReceived(double busCurrent) in ../../Epsilon-Dashboard/ViewLayer/DisplayDashboard/DisplayDashboardView/DisplayDashboardView.cpp:87

**Comment by bill-luu** [comment]
Can you push up a copy of the branch you were working on so we can replicate the issues?

**Comment by jeffh1996** [comment]
Pushed it just now. Its called JsonTest. Its pretty messy and theres a few parts hardcoded in since I originally planned to do testing on it only and delete it afterwards. The branch that I am doing however, is able to pull data from the RabbitMq server (although there are still a few severe problems such as program freezing). The missing signals should still be visible when running. Most of these signals were present in the master branch as well.

**Comment by bill-luu** [comment]
I think I figured it out! Check out the latest commit I made on that branch.

The issue was that we were declaring our signals wrong all throughout the program - signals should be in the format :    
`connect(&keyMotorData_, SIGNAL(motorZeroReceived(KeyMotor)), this, SIGNAL(motorZeroReceived(KeyMotor)));`
instead of: 
`connect(&keyMotorData_, SIGNAL(motorZeroReceived(KeyMotor keyMotorData)), this, SIGNAL(motorZeroReceived(KeyMotor keyMotorData));`

Then the reason that the program crashes is because of something we're doing wrong with the QLists in the mppts, so I commented that out.

The branch now should be able to run display mode correctly and react to the test tool.
![image](https://user-images.githubusercontent.com/15304203/32015724-2cca7652-b97f-11e7-8fbf-76120b1a64c7.png)

Can you make a PR that fixes all of the signals in the program, and figure out how the qList issue? Also fix the mistake in BatteryFaultsPresenter, also fixed in the branch.
